// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqyzwgkzgxwfywizwnkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxeXp3Z2t6Z3h3Znl3aXp3bmt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0MjEwNDIsImV4cCI6MjA4OTk5NzA0Mn0.nvSpadUmGIU5Uivfbu_OVOpudyn4R9cbaZCg_-cWRUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});